"""PC Macro Builder application package."""

from .rally_hot_path_runtime import install_rally_hot_path_runtime
from .rally_three_team_runtime import install_rally_three_team_runtime

install_rally_three_team_runtime()
install_rally_hot_path_runtime()

from .rally_hot_path_v7_runtime import install_rally_hot_path_v7_runtime

install_rally_hot_path_v7_runtime()

from .rally_hot_path_v8_runtime import install_rally_hot_path_v8_runtime

install_rally_hot_path_v8_runtime()

from .rally_hot_path_v9_runtime import install_rally_hot_path_v9_runtime

install_rally_hot_path_v9_runtime()

from .rally_hot_path_v10_runtime import install_rally_hot_path_v10_runtime

install_rally_hot_path_v10_runtime()

from .rally_hot_path_v11_runtime import install_rally_hot_path_v11_runtime

install_rally_hot_path_v11_runtime()

from .rally_hot_path_v12_runtime import install_rally_hot_path_v12_runtime

install_rally_hot_path_v12_runtime()

from .rally_hot_path_v13_runtime import install_rally_hot_path_v13_runtime

install_rally_hot_path_v13_runtime()

from .rally_hot_path_v14_runtime import install_rally_hot_path_v14_runtime

install_rally_hot_path_v14_runtime()

from .rally_hot_path_v15_runtime import install_rally_hot_path_v15_runtime

install_rally_hot_path_v15_runtime()

from .rally_hot_path_v16_runtime import install_rally_hot_path_v16_runtime

install_rally_hot_path_v16_runtime()

from .rally_hot_path_v17_runtime import install_rally_hot_path_v17_runtime

install_rally_hot_path_v17_runtime()

from .rally_hot_path_v18_runtime import install_rally_hot_path_v18_runtime

install_rally_hot_path_v18_runtime()

from .rally_hot_path_v19_runtime import install_rally_hot_path_v19_runtime

install_rally_hot_path_v19_runtime()

from .rally_hot_path_v20_runtime import install_rally_hot_path_v20_runtime

install_rally_hot_path_v20_runtime()

from .rally_hot_path_v21_runtime import install_rally_hot_path_v21_runtime

install_rally_hot_path_v21_runtime()

from .rally_hot_path_v22_runtime import install_rally_hot_path_v22_runtime

install_rally_hot_path_v22_runtime()

from .rally_hot_path_v23_runtime import install_rally_hot_path_v23_runtime

install_rally_hot_path_v23_runtime()

from .rally_hot_path_v24_runtime import install_rally_hot_path_v24_runtime

install_rally_hot_path_v24_runtime()

del install_rally_three_team_runtime
del install_rally_hot_path_runtime
del install_rally_hot_path_v7_runtime
del install_rally_hot_path_v8_runtime
del install_rally_hot_path_v9_runtime
del install_rally_hot_path_v10_runtime
del install_rally_hot_path_v11_runtime
del install_rally_hot_path_v12_runtime
del install_rally_hot_path_v13_runtime
del install_rally_hot_path_v14_runtime
del install_rally_hot_path_v15_runtime
del install_rally_hot_path_v16_runtime
del install_rally_hot_path_v17_runtime
del install_rally_hot_path_v18_runtime
del install_rally_hot_path_v19_runtime
del install_rally_hot_path_v20_runtime
del install_rally_hot_path_v21_runtime
del install_rally_hot_path_v22_runtime
del install_rally_hot_path_v23_runtime
del install_rally_hot_path_v24_runtime
