"""PC Macro Builder application package."""

from .rally_hot_path_runtime import install_rally_hot_path_runtime
from .rally_three_team_runtime import install_rally_three_team_runtime

install_rally_three_team_runtime()
install_rally_hot_path_runtime()

from .rally_hot_path_v7_runtime import install_rally_hot_path_v7_runtime

install_rally_hot_path_v7_runtime()

from .rally_hot_path_v8_runtime import install_rally_hot_path_v8_runtime

install_rally_hot_path_v8_runtime()

from .rally_hot_path_v9_runtime import install_rally_hot_path_v9_runtime

install_rally_hot_path_v9_runtime()

from .rally_hot_path_v10_runtime import install_rally_hot_path_v10_runtime

install_rally_hot_path_v10_runtime()

del install_rally_three_team_runtime
del install_rally_hot_path_runtime
del install_rally_hot_path_v7_runtime
del install_rally_hot_path_v8_runtime
del install_rally_hot_path_v9_runtime
del install_rally_hot_path_v10_runtime
